### ISSUE TITLE
Unable to install Flask-2.2.5-py3-none-any.whl 

### ISSUE THREAD

**Issue by Blason** [JMousqueton/api.ransomware.live#3]
Collecting Flask==2.2.5
  Using cached Flask-2.2.5-py3-none-any.whl (101 kB)
ERROR: Could not find a version that satisfies the requirement Flask-RESTx==0.5.2 (from versions: 0.0.1.dev0, 0.1.0, 0.1.1, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 1.0.0, 1.0.1, 1.0.3, 1.0.5, 1.0.6, 1.1.0)

**Comment by JMousqueton** [comment]
I've just rollbacked requirements.txt to the last good version.

**Comment by Blason** [comment]
Done!! Thanks
